### ISSUE TITLE
npm install . fails

### ISSUE THREAD

**Issue by holgerschill** [mbana/monaco-go#1]
~/dev/repos/monaco-go (master) npm install .
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> monaco-go@1.2.1 prepublish /Users/schill/dev/repos/monaco-go
> gulp release

[18:56:00] Using gulpfile ~/dev/repos/monaco-go/gulpfile.js
[18:56:00] Starting 'clean-release'...
[18:56:00] Starting 'clean-out'...
[18:56:00] Finished 'clean-release' after 5.82 ms
[18:56:00] Finished 'clean-out' after 3.59 ms
[18:56:00] Starting 'compile'...
/Users/schill/dev/repos/monaco-go/node_modules/vscode-jsonrpc/lib/main.d.ts(2,1): error TS2688: Cannot find type definition file for 'node'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-jsonrpc/lib/main.d.ts(171,62): error TS2503: Cannot find namespace 'NodeJS'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-jsonrpc/lib/main.d.ts(171,99): error TS2503: Cannot find namespace 'NodeJS'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-jsonrpc/lib/messageReader.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-jsonrpc/lib/messageReader.d.ts(2,30): error TS2307: Cannot find module 'child_process'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-jsonrpc/lib/messageReader.d.ts(39,27): error TS2503: Cannot find namespace 'NodeJS'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-jsonrpc/lib/messageReader.d.ts(48,26): error TS2503: Cannot find namespace 'NodeJS'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-jsonrpc/lib/messageWriter.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-jsonrpc/lib/messageWriter.d.ts(2,30): error TS2307: Cannot find module 'child_process'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-jsonrpc/lib/messageWriter.d.ts(24,27): error TS2503: Cannot find namespace 'NodeJS'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-jsonrpc/lib/messageWriter.d.ts(30,26): error TS2503: Cannot find namespace 'NodeJS'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/codeConverter.d.ts(1,23): error TS2307: Cannot find module 'vscode'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main.d.ts(2,21): error TS2307: Cannot find module 'child_process'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main.d.ts(4,117): error TS2307: Cannot find module 'vscode'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main.d.ts(15,13): error TS2503: Cannot find namespace 'NodeJS'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main.d.ts(16,13): error TS2503: Cannot find namespace 'NodeJS'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/protocolCompletionItem.d.ts(1,23): error TS2307: Cannot find module 'vscode'.
/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/protocolConverter.d.ts(1,23): error TS2307: Cannot find module 'vscode'.
src/fillers/vscode-nls.ts(6,63): error TS2307: Cannot find module 'vscode-nls'.
src/language-client/monaco-language-client.ts(10,2): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'Message'.
src/language-client/web-socket-reader.ts(4,2): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'DataCallback'.
src/language-client/web-socket-reader.ts(5,2): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'MessageWriter'.
src/language-client/web-socket-reader.ts(5,17): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'MessageReader'.
src/language-client/web-socket-reader.ts(6,2): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'Message'.
src/language-client/web-socket-reader.ts(6,11): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'PartialMessageInfo'.
src/language-client/web-socket-stream.ts(2,2): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'DataCallback'.
src/language-client/web-socket-stream.ts(3,2): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'MessageWriter'.
src/language-client/web-socket-stream.ts(3,17): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'MessageReader'.
src/language-client/web-socket-stream.ts(4,2): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'Message'.
src/language-client/web-socket-stream.ts(4,11): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'PartialMessageInfo'.
src/language-client/web-socket-writer.ts(6,2): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'DataCallback'.
src/language-client/web-socket-writer.ts(7,2): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'MessageWriter'.
src/language-client/web-socket-writer.ts(7,17): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'MessageReader'.
src/language-client/web-socket-writer.ts(8,2): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'Message'.
src/language-client/web-socket-writer.ts(8,11): error TS2305: Module '"/Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main"' has no exported member 'PartialMessageInfo'.
[18:56:03] TypeScript: 36 semantic errors
[18:56:03] TypeScript: emit succeeded (with errors)
[18:56:03] Finished 'compile' after 2.21 s
[18:56:03] Starting 'release'...
Error: Error: Parse error using esprima for file: /Users/schill/dev/repos/monaco-go/node_modules/vscode-languageclient/lib/main.js
Error: Line 28: Unexpected reserved word
In module tree:
    vs/language/go/goMode
      vs/language/go/language-client/monaco-language-client

    at /Users/schill/dev/repos/monaco-go/node_modules/requirejs/bin/r.js:23419:47

    at /Users/schill/dev/repos/monaco-go/node_modules/requirejs/bin/r.js:23960:19
    at /Users/schill/dev/repos/monaco-go/node_modules/requirejs/bin/r.js:2896:39
    at /Users/schill/dev/repos/monaco-go/node_modules/requirejs/bin/r.js:2836:25
    at Function.prim.nextTick (/Users/schill/dev/repos/monaco-go/node_modules/requirejs/bin/r.js:23794:9)
    at Object.errback (/Users/schill/dev/repos/monaco-go/node_modules/requirejs/bin/r.js:2835:26)
    at Object.callback (/Users/schill/dev/repos/monaco-go/node_modules/requirejs/bin/r.js:2821:23)
    at Object.then (/Users/schill/dev/repos/monaco-go/node_modules/requirejs/bin/r.js:2875:23)
    at build (/Users/schill/dev/repos/monaco-go/node_modules/requirejs/bin/r.js:23919:12)
    at runBuild (/Users/schill/dev/repos/monaco-go/node_modules/requirejs/bin/r.js:25622:17)
    at Object.execCb (/Users/schill/dev/repos/monaco-go/node_modules/requirejs/bin/r.js:1869:33)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "."
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! monaco-go@1.2.1 prepublish: `gulp release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the monaco-go@1.2.1 prepublish script 'gulp release'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the monaco-go package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp release
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs monaco-go
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls monaco-go
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/schill/dev/repos/monaco-go/npm-debug.log

**Comment by mbana** [comment]
I'd suggest you run the Docker build.

that said, run the script as per:

* https://github.com/mbana/monaco-go#locally
* then uncomment out the bower install lines in https://github.com/mbana/monaco-go/blob/master/build/all.sh#L23.

i could possibly add the build dirs as volumes so that one could modify the src file and see the changes in the docker container - not now though.

---

if that still fails do:

```sh
$ docker pull mohamedbana/monaco-go:7b65dcb && docker run -p 8080:8080 -p 4389:4389 -it mohamedbana/monaco-go:7b65dcb
```

**Comment by holgerschill** [comment]
Works when running all.sh script directly in root of the repo.
